### ISSUE TITLE
Running example get "Segmentation fault"

### ISSUE THREAD

**Issue by Lizard-King101** [CoolCyberBrain/RPi-MFRC522-nodejs#1]
followed instructions and cloned example after getting this issue can still getting "segmentation Fault"
running; 
Node:    12.18.4
npm:      6.14.6
raspberry pi 3 B

**Comment by Calvin-LL** [comment]
Any chance you can provide the stack trace or error message? That would narrow the problem down signifincantly.

**Comment by Lizard-King101** [comment]
okay never mind that was because I wasn't running under sudo but still am unable to read the cards however. I downloaded another plugin for RFID reading and it had an error that looked like it would be causing all my issues with GPIO pins, it says that the GPIO pins are in use by /sys/class/gpio. not sure if that's relevant or not.

**Comment by Lizard-King101** [comment]
no?

**Comment by Calvin-LL** [comment]
> okay never mind that was because I wasn't running under sudo but still am unable to read the cards however. I downloaded another plugin for RFID reading and it had an error that looked like it would be causing all my issues with GPIO pins, it says that the GPIO pins are in use by /sys/class/gpio. not sure if that's relevant or not.

I've never seen that error before. I'll try the library on a fresh install today to see what's going on.

**Comment by Calvin-LL** [comment]
I can reproduce the problem now. Working on a fix

**Comment by Calvin-LL** [comment]
I can't reproduce the issure you're describing, it is probably not a bug with this library but rather your setup, try resetting your raspberry pi and try again.

**Comment by Lizard-King101** [comment]
Yea turned out to be DOA hardware tested it with arduino and python neither worked. Ordered a new rc522 module and instantly got cards to read
